// SPDX-License-Identifier: MIT
// Copyright 2026 Nicolas Moreno
/**
 * Bundle-related copy keys. Used by both
 * `zarel trace bundle` (download) and `zarel verify` (offline verification),
 * and by the embedded README.md inside generated archives.
 */

import { buildSubdomainOrigin } from './deployment-url.js';

export interface BundleMessages {
    readonly readme: {
        readonly title: (traceId: string) => string;
        readonly intro: string;
        readonly contents: string;
        readonly verifyInstructions: string;
        readonly footer: string;
    };
    readonly verify: {
        readonly success: {
            readonly signatureValid: (kid: string) => string;
            readonly contentHashesMatch: string;
            readonly attestationReproduces: string;
            readonly summary: (traceId: string, tenant: string, verifiedAt: string) => string;
        };
        readonly errors: {
            readonly signatureInvalid: string;
            readonly contentHashMismatch: (path: string) => string;
            readonly kidUnknown: (kid: string) => string;
            readonly attestationDoesNotReproduce: string;
            readonly trustKeysMissing: string;
            readonly bundleMalformed: (reason: string) => string;
        };
    };
    readonly export: {
        readonly inFlight: 'Trace is still in flight (no terminal outcome). Bundle export rejected; wait for the trace to settle.';
        readonly tooLarge: 'Bundle would exceed the 200 MB hard cap. Narrow the trace scope or open a follow-up to design bundle splitting (out of scope for v1).';
    };
    readonly legacyLimitations: string;
}

export const bundleMessages: BundleMessages = {
    readme: {
        title: (traceId): string => `# Evidence bundle for trace ${traceId}`,
        intro: 'This bundle was generated by Zarel as portable, signed evidence of an agent decision. It is independently verifiable using the `zarel verify` command and the deployment\'s public trust keys at `https://<deployment>/.well-known/zarel-trust-keys.json`.',
        contents: 'Contents:\n- trace.json: machine-readable chronology of every governance stage.\n- trace.pdf: human-readable summary suitable for printing.\n- spec/: the contract deployed at the time of execution.\n- entities_snapshot.json: the state of records the trace touched.\n- replay_attestation.json: the result of an automatic deterministic replay.\n- manifest.json + manifest.sig: cryptographic proof of authenticity.',
        verifyInstructions: 'To verify offline:\n  zarel verify <this-bundle>.tar.gz --keys <trust-keys.json>',
        footer: `For more, see ${buildSubdomainOrigin('docs')}/operations/evidence-bundles`,
    },
    verify: {
        success: {
            signatureValid: (kid): string => `✓ Manifest signature valid (kid=${kid}, Ed25519).`,
            contentHashesMatch: '✓ Content hashes match.',
            attestationReproduces: '✓ Replay attestation reproduces deterministic match.',
            summary: (traceId, tenant, verifiedAt): string =>
                `Bundle: trace ${traceId}\nTenant: ${tenant}\nVerified at: ${verifiedAt}`,
        },
        errors: {
            signatureInvalid: 'Manifest signature does NOT verify.',
            contentHashMismatch: (path): string => `Content hash mismatch for ${path}.`,
            kidUnknown: (kid): string =>
                `Bundle signed with kid=${kid}, but no matching public key found in the local trust-keys file. Run \`zarel trust-keys fetch <deployment>\` to refresh.`,
            attestationDoesNotReproduce: 'Replay attestation embedded in the bundle does NOT reproduce when re-run locally.',
            trustKeysMissing: 'Trust-keys file not found. Pass --keys <path> or run `zarel trust-keys fetch <deployment>`.',
            bundleMalformed: (reason): string => `Bundle malformed: ${reason}.`,
        },
    },
    export: {
        inFlight: 'Trace is still in flight (no terminal outcome). Bundle export rejected; wait for the trace to settle.',
        tooLarge: 'Bundle would exceed the 200 MB hard cap. Narrow the trace scope or open a follow-up to design bundle splitting (out of scope for v1).',
    },
    legacyLimitations: 'Pre-feature trace — best-effort replay. Entity-state reconstruction may be incomplete; some governance stages may be marked "unknown".',
};
